apiVersion: v1
kind: ConfigMap
metadata:
  name: contoso-air-config
  labels:
    app.kubernetes.io/name: contoso-air
    kubernetes.azure.com/generator: devhub
data:
  AZURE_OPENAI_API_VERSION: 2024-12-01-preview
  AZURE_OPENAI_DEPLOYMENT: gpt-5-mini
  CHAT_PROVIDER: azure
  LOG_CHAT: 'true'
